# `Julia` basics: Linear Algebra and Functions

Here we will review some basics of `Julia`'s linear algebra offerings.

## Arrays, Matrices, and Vectors

`Julia` offers vectors (1-dimensional objects that are neither row nor column) and matrices (2-dimensional objects that can have 1 or more rows or columns)

### Vectors

Vectors in `Julia` are one-dimensional:

In [1]:
x=rand(5)

5-element Array{Float64,1}:
 0.978551
 0.468803
 0.543615
 0.246352
 0.700059

In [2]:
size(x)

(5,)

In [3]:
y=rand(5)

5-element Array{Float64,1}:
 0.168236
 0.714346
 0.60362 
 0.113934
 0.537309

In [4]:
x.*y

5-element Array{Float64,1}:
 0.164627 
 0.334887 
 0.328137 
 0.0280678
 0.376148 

In [5]:
x*y'

5×5 Array{Float64,2}:
 0.164627   0.699023  0.590673  0.11149    0.525784
 0.0788695  0.334887  0.282978  0.0534124  0.251892
 0.0914555  0.388329  0.328137  0.061936   0.292089
 0.0414454  0.175981  0.148703  0.0280678  0.132368
 0.117775   0.500084  0.42257   0.0797603  0.376148

In [6]:
x'*y

1-element Array{Float64,1}:
 1.23187

In [7]:
dot(x,y)

1.2318672776134991

Key nuances:
- The element-wise product of two vectors is a vector.
- The matrix product is a 1-element vector, *NOT* a scalar
- The dot product is a scalar

### Matrices

#### Initializing matrices

In [8]:
z = Array(Float64,3,2)

3×2 Array{Float64,2}:
 1.10181e-314  1.10181e-314
 1.10181e-314  1.11382e-314
 1.10181e-314  1.0656e-314 

In [9]:
z = ones(Bool,3,2)

3×2 Array{Bool,2}:
 true  true
 true  true
 true  true

In [10]:
z = ones(3,2)

3×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

#### Concatenation

In [11]:
z = [z;[1 2]]

4×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  2.0

In [12]:
x = cat(1,5,6,7)

3-element Array{Int64,1}:
 5
 6
 7

In [13]:
y = cat(2,8,9,10)

1×3 Array{Int64,2}:
 8  9  10

#### Indexing

Index elements of a vector or matrix using brackets `[]`

In [14]:
z[2,1]

1.0

In [15]:
z[2:end,1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [16]:
z[:,2]

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 2.0

In [17]:
z[1:2:end,2]

2-element Array{Float64,1}:
 1.0
 1.0

You can also index with a boolean vector:

In [18]:
z[z[:,2].==1,:]

3×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [19]:
z[z[:,2].!=1,:]

1×2 Array{Float64,2}:
 1.0  2.0

## Linear Algebra

`Julia` offers many of the same linear algebra functions as `Matlab` and `R`. Here, we'll cover some basic operations. More complex operations (e.g. singular value decomposition) are also supported.

Addition `+` and subtraction `-` follow basic matrix rules. Note that adding a scalar to a matrix will add the scalar to each element.

In [20]:
z+1

4×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0
 2.0  2.0
 2.0  3.0

In [21]:
z-z

4×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

`*` in `Julia` represents matrix multiplication

In [22]:
z*repmat(y,2,1)

4×3 Array{Float64,2}:
 16.0  18.0  20.0
 16.0  18.0  20.0
 16.0  18.0  20.0
 24.0  27.0  30.0

Use `\` or `/` to invert matrices

In [23]:
x= rand(3,3);

In [24]:
x\eye(3)

3×3 Array{Float64,2}:
 -7.45409   7.99055   2.45772
  3.42861  -2.33951  -1.26174
  7.74528  -8.70005  -1.00836

In [25]:
eye(3)/x

3×3 Array{Float64,2}:
 -7.45409   7.99055   2.45772
  3.42861  -2.33951  -1.26174
  7.74528  -8.70005  -1.00836

### Element-wise operations

As in `Matlab`, a `.` in front of an operator causes it to be evaluated element-wise: 

In [26]:
rand(3,3).*randn(3,3)

3×3 Array{Float64,2}:
  1.65898   -0.851963  0.404567
 -0.757503  -0.199346  0.138904
 -0.188084   0.227847  0.102997

Unlike `Matlab`, however, the `.` must precede *any* operator

In [27]:
rand(3)>.5

LoadError: MethodError: no method matching isless(::Float64, ::Array{Float64,1})
Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:283
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
  isless(::Real, ::AbstractFloat) at operators.jl:41
  ...

In [28]:
rand(3).>.5

3-element BitArray{1}:
 false
  true
 false

In [29]:
rand(3).==.5

3-element BitArray{1}:
 false
 false
 false

## Comprehensions

Comprehensions in `Julia` are a general and compact way to construct arrays. The general syntax is:

`A = [ F(x,y,...) for x=rx, y=ry, ... ]`

meaning that `F(x,y,...)` is evaluated with the variables `x`, `y`, etc. taking on each value in their given list of values.

As an example, we can construct a "weighted-neighbor average" of elements in an a vector:

In [30]:
const zed = rand(8)

8-element Array{Float64,1}:
 0.00578284
 0.538936  
 0.565143  
 0.0745245 
 0.576913  
 0.621932  
 0.853102  
 0.968397  

In [31]:
M=[ 0.25*zed[i-1] + 0.5*zed[i] + 0.25*zed[i+1] for i=2:length(zed)-1 ]

6-element Array{Float64,1}:
 0.412199
 0.435937
 0.322776
 0.46257 
 0.66847 
 0.824133

## Looping

Looping in `Julia` has flexible syntax

In [32]:
zz = rand(5)
for i=1:length(zz)
    println(zz[i])
end

0.37712996800224374
0.953924625076064
0.027698499021464373
0.27045153501658525
0.24040735361581822


We can identically evaluate the loop using the following syntax:

In [33]:
for i in 1:length(zz)
    println(zz[i])
end

0.37712996800224374
0.953924625076064
0.027698499021464373
0.27045153501658525
0.24040735361581822


## Vectorization

While looping is fast in `Julia`, one can also quite easily perform matrix and vectorized operations in an intuitive way (unlike compiled languages like `C` and `FORTRAN`)

Keep in mind that there are times when looping is faster than vectorization and vice versa. We will cover specifics later.

## Functions

Functions in `Julia` follow these rules:
1. `function` must be the first word
2. inputs to the function are listed in parentheses after the function name
3. outputs to the function are listed in the last line
4. `end` must be the last word on its own line

In [34]:
function myfun(a,b)
    c=a*b;
    return c
end

myfun (generic function with 1 method)

In [35]:
myfun(5,6)

30

In [36]:
myfun([5;5],[6 1])

2×2 Array{Int64,2}:
 30  5
 30  5

Note that, because we used `*` to compute `c` in the function, it works with both scalars and conformable matrices.

In [37]:
function failer(r::Array)
    r = r + 1
end

function adder(r::Array)
    r[:] = r + 1
end

adder (generic function with 1 method)

In [38]:
testarr = [0, 0]

failer(testarr)

println(testarr)

[0,0]


### Multiple outputs

Functions with multiple outputs can be returned using tuples:

In [39]:
function myfun2(a,b)
    c=a*b;
    return c,a,b
end

myfun2 (generic function with 1 method)

In [40]:
product,in1,in2 = myfun2(5,6)

(30,5,6)

In [41]:
product

30

In [42]:
in1

5

In [43]:
in2

6

If you forget to specify the multiple outputs and instead only return 1 output, the new output is a tuple:

In [44]:
product1 = myfun2(5,5)

(25,5,5)

In [45]:
product1

(25,5,5)