# `Julia` basics: Linear Algebra and Functions

Here we will review some basics of `Julia`'s linear algebra offerings.

## Arrays, Matrices, and Vectors

`Julia` offers vectors (1-dimensional objects that are neither row nor column) and matrices (2-dimensional objects that can have 1 or more rows or columns)

### Vectors

Vectors in `Julia` are one-dimensional:

In [1]:
x=rand(5)

5-element Array{Float64,1}:
 0.852695
 0.881251
 0.379214
 0.959642
 0.696772

In [2]:
size(x)

(5,)

In [10]:
y=rand(5)

5-element Array{Float64,1}:
 0.0552599
 0.930213 
 0.168369 
 0.612629 
 0.683231 

In [11]:
x.*y

5-element Array{Float64,1}:
 0.0471198
 0.819752 
 0.063848 
 0.587904 
 0.476057 

In [12]:
x*y'

5x5 Array{Float64,2}:
 0.0471198  0.793188  0.143568  0.522385  0.582588
 0.0486978  0.819752  0.148376  0.53988   0.602098
 0.0209553  0.35275   0.063848  0.232317  0.259091
 0.0530297  0.892672  0.161574  0.587904  0.655658
 0.0385035  0.648147  0.117315  0.426862  0.476057

In [13]:
x'*y

1-element Array{Float64,1}:
 1.99468

In [14]:
dot(x,y)

1.9946804046540076

Key nuances:
- The element-wise product of two vectors is a vector.
- The matrix product is a 1-element vector, *NOT* a scalar
- The dot product is a scalar

### Matrices

#### Initializing matrices

In [15]:
z = Array(Float64,3,2)

3x2 Array{Float64,2}:
 4.24399e-314  0.0
 1.061e-314    0.0
 0.0           0.0

In [16]:
z = ones(Bool,3,2)

3x2 Array{Bool,2}:
 true  true
 true  true
 true  true

In [17]:
z = ones(3,2)

3x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

#### Concatenation

In [18]:
z = [z;[1 2]]

4x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  2.0

In [19]:
x = cat(1,5,6,7)

3-element Array{Int64,1}:
 5
 6
 7

In [20]:
y = cat(2,8,9,10)

1x3 Array{Int64,2}:
 8  9  10

#### Indexing

Index elements of a vector or matrix using brackets `[]`

In [23]:
z[2,1]

1.0

In [24]:
z[2:end,1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [25]:
z[:,2]

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 2.0

In [26]:
z[1:2:end,2]

2-element Array{Float64,1}:
 1.0
 1.0

You can also index with a boolean vector:

In [67]:
z[z[:,2].==1,:]

3x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [70]:
z[z[:,2].!=1,:]

1x2 Array{Float64,2}:
 1.0  2.0

## Linear Algebra

`Julia` offers many of the same linear algebra functions as `Matlab` and `R`. Here, we'll cover some basic operations. More complex operations (e.g. singular value decomposition) are also supported.

Addition `+` and subtraction `-` follow basic matrix rules. Note that adding a scalar to a matrix will add the scalar to each element.

In [27]:
z+1

4x2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0
 2.0  2.0
 2.0  3.0

In [28]:
z-z

4x2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

`*` in `Julia` represents matrix multiplication

In [29]:
z*repmat(y,2,1)

4x3 Array{Float64,2}:
 16.0  18.0  20.0
 16.0  18.0  20.0
 16.0  18.0  20.0
 24.0  27.0  30.0

Use `\` or `/` to invert matrices

In [35]:
x= rand(3,3);

In [36]:
x\eye(3)

3x3 Array{Float64,2}:
  7.21931   0.882785  -5.72388  
 -5.75474   1.20508    4.27957  
  1.71034  -0.807295  -0.0145169

In [37]:
eye(3)/x

3x3 Array{Float64,2}:
  7.21931   0.882785  -5.72388  
 -5.75474   1.20508    4.27957  
  1.71034  -0.807295  -0.0145169

### Element-wise operations

As in `Matlab`, a `.` in front of an operator causes it to be evaluated element-wise: 

In [38]:
rand(3,3).*randn(3,3)

3x3 Array{Float64,2}:
  0.285639   1.10301    -0.155867
  0.0940905  0.0107927  -0.421785
 -0.786684   0.0440169  -0.984853

Unlike `Matlab`, however, the `.` must precede *any* operator

In [41]:
rand(3)>.5

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Float64, ::Array{Float64,1})
Closest candidates are:
  isless(::Float64, !Matched::Float64)
  isless(::AbstractFloat, !Matched::AbstractFloat)
  isless(::Real, !Matched::AbstractFloat)
  ...
while loading In[41], in expression starting on line 1

In [39]:
rand(3).>.5

3-element BitArray{1}:
  true
 false
  true

In [40]:
rand(3).==.5

3-element BitArray{1}:
 false
 false
 false

## Comprehensions

Comprehensions in `Julia` are a general and compact way to construct arrays. The general syntax is:

`A = [ F(x,y,...) for x=rx, y=ry, ... ]`

meaning that `F(x,y,...)` is evaluated with the variables `x`, `y`, etc. taking on each value in their given list of values.

As an example, we can construct a "weighted-neighbor average" of elements in an a vector:

In [57]:
const zed = rand(8)

8-element Array{Float64,1}:
 0.115584 
 0.421506 
 0.809837 
 0.250175 
 0.847397 
 0.460844 
 0.189869 
 0.0410234

In [59]:
M=[ 0.25*zed[i-1] + 0.5*zed[i] + 0.25*zed[i+1] for i=2:length(zed)-1 ]

6-element Array{Float64,1}:
 0.442108
 0.572839
 0.539396
 0.601453
 0.489738
 0.220401

## Looping

Looping in `Julia` has flexible syntax

In [68]:
zz = rand(5)
for i=1:length(zz)
    println(zz[i])
end

0.3609490393239405
0.1934427651276307
0.33493661827490073
0.8646933527930136
0.34381710559371825


We can identically evaluate the loop using the following syntax:

In [69]:
for i in 1:length(zz)
    println(zz[i])
end

0.3609490393239405
0.1934427651276307
0.33493661827490073
0.8646933527930136
0.34381710559371825


## Vectorization

While looping is fast in `Julia`, one can also quite easily perform matrix and vectorized operations in an intuitive way (unlike compiled languages like `C` and `FORTRAN`)

Keep in mind that there are times when looping is faster than vectorization and vice versa. We will cover specifics later.

## Functions

Functions in `Julia` follow these rules:
1. `function` must be the first word
2. inputs to the function are listed in parentheses after the function name
3. outputs to the function are listed in the last line
4. `end` must be the last word on its own line

In [49]:
function myfun(a,b)
    c=a*b;
    return c
end

myfun (generic function with 1 method)

In [45]:
myfun(5,6)

30

In [46]:
myfun([5;5],[6 1])

2x2 Array{Int64,2}:
 30  5
 30  5

Note that, because we used `*` to compute `c` in the function, it works with both scalars and conformable matrices.

In [1]:
function failer(r::Array)
    r = r + 1
end

function adder(r::Array)
    r[:] = r + 1
end

adder (generic function with 1 method)

In [3]:
testarr = [0, 0]

failer(testarr)

println(testarr)

[0,0]


### Multiple outputs

Functions with multiple outputs can be returned using tuples:

In [48]:
function myfun2(a,b)
    c=a*b;
    return c,a,b
end

myfun2 (generic function with 1 method)

In [50]:
product,in1,in2 = myfun2(5,6)

(30,5,6)

In [51]:
product

30

In [52]:
in1

5

In [53]:
in2

6

If you forget to specify the multiple outputs and instead only return 1 output, the new output is a tuple:

In [55]:
product1 = myfun2(5,5)

(25,5,5)

In [56]:
product1

(25,5,5)